export const CONFIG = {
  http: {
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    timeout: 60000,
    retries: 3,
    retryDelay: 800,
    retryStatusCodes: [429, 500, 502, 503, 504],
  },

  rss: {
    defaultOpmlPath: './feeds/follow.opml',
    maxConcurrency: 20,
    feedTimeout: 60000,
    replacements: {} as Record<string, string>,
    skipPrefixes: [
      'https://rsshub.app/telegram/channel/',
      'https://rsshub.app/jike/',
      'https://rsshub.app/bilibili/',
      'https://rsshub.app/zhihu/',
      'https://rsshub.app/xiaoyuzhou/podcast/',
      'https://rsshub.app/xyzrank',
      'https://rsshub.app/mittrchina/hot',
      'https://wechat2rss.bestblogs.dev/',
      'https://werss.bestblogs.dev/',
    ],
    skipExact: new Set([
      'https://rachelbythebay.com/w/atom.xml',
      'https://flak.tedunangst.com/rss',
    ]),
  },

  waytoagi: {
    defaultUrl:
      'https://waytoagi.feishu.cn/wiki/QPe5w5g7UisbEkkow8XcDmOpn8e?fromScene=spaceOverview',
    historyFallback: 'https://waytoagi.feishu.cn/wiki/FjiOwWp2giA7hRk6jjfcPioCnAc',
  },

  timezone: 'Asia/Kolkata',

  filter: {
    aiKeywords: [
      // Core AI terms
      'aigc',
      'llm',
      'gpt',
      'claude',
      'gemini',
      'deepseek',
      'openai',
      'anthropic',
      'hugging face',
      'transformer',
      'prompt',
      'diffusion',
      'agent',
      'artificial intelligence',
      'machine learning',
      'deep learning',
      'neural network',
      'foundation model',
      'large language model',
      'generative ai',
      'multimodal',
      'fine-tuning',
      'inference',
      // Healthcare AI terms
      'healthcare ai',
      'medical ai',
      'clinical ai',
      'health ai',
      'ai diagnosis',
      'ai diagnostics',
      'clinical decision support',
      'precision medicine',
      'personalized medicine',
      'digital health',
      'telemedicine',
      'telehealth',
      'ehr',
      'electronic health record',
      'medical imaging',
      'radiology ai',
      'drug discovery',
      'clinical trial',
      'fda approval',
      'biomarker',
      'genomics',
      'proteomics',
      'wearable',
      // Pathology & Lab Medicine terms
      'pathology',
      'digital pathology',
      'computational pathology',
      'histopathology',
      'cytology',
      'histology',
      'whole slide imaging',
      'wsi',
      'laboratory medicine',
      'lab medicine',
      'clinical laboratory',
      'immunohistochemistry',
      'ihc',
      'molecular pathology',
      'surgical pathology',
      'anatomic pathology',
      'clinical pathology',
      'hematopathology',
      'dermatopathology',
      'neuropathology',
      'pathologist',
      'microscopy',
      'biopsy',
      'tissue analysis',
      'cell segmentation',
      'stain normalization',
      'h&e stain',
      'ki-67',
      'biobank',
      'specimen',
      // General medicine & clinical terms
      'clinical',
      'patient',
      'diagnosis',
      'treatment',
      'therapy',
      'prognosis',
      'outcome',
      'mortality',
      'morbidity',
      'randomized controlled',
      'meta-analysis',
      'systematic review',
      'cohort study',
      'case report',
      'evidence-based',
      // Specialty-specific terms
      'oncology',
      'cancer',
      'tumor',
      'tumour',
      'carcinoma',
      'lymphoma',
      'leukemia',
      'melanoma',
      'chemotherapy',
      'immunotherapy',
      'cardiology',
      'cardiac',
      'cardiovascular',
      'heart failure',
      'coronary',
      'arrhythmia',
      'myocardial',
      'neurology',
      'neurological',
      'alzheimer',
      'parkinson',
      'stroke',
      'epilepsy',
      'dementia',
      'neurodegenerative',
      'surgery',
      'surgical',
      'laparoscopic',
      'robotic surgery',
      'transplant',
      'radiology',
      'radiologist',
      'ct scan',
      'mri',
      'ultrasound',
      'mammography',
      'x-ray',
      'microbiology',
      'infectious disease',
      'antimicrobial',
      'antibiotic',
      'resistance',
      'sepsis',
      'bacteria',
      'viral',
      'ophthalmology',
      'retinal',
      'glaucoma',
      'cataract',
      'macular',
      'pediatric',
      'neonatal',
      'psychiatry',
      'mental health',
      'depression',
      'anxiety',
      'schizophrenia',
      'dermatology',
      'skin cancer',
      'psoriasis',
      'orthopedic',
      'fracture',
      'musculoskeletal',
      'obstetrics',
      'gynecology',
      'maternal',
      'prenatal',
      'emergency medicine',
      'critical care',
      'intensive care',
      'trauma',
      'public health',
      'epidemiology',
      'vaccine',
      'pandemic',
      'pharmacology',
      'drug development',
      'pharmacokinetics',
      'biochemistry',
      'enzyme',
      'metabolism',
      'assay',
      'genome',
      'genetic',
      'sequencing',
      'crispr',
      'bioinformatics',
      'gene therapy',
    ],
    techKeywords: [
      'robot',
      'robotics',
      'embodied',
      'autonomous',
      'vision',
      'computer vision',
      'chip',
      'semiconductor',
      'cuda',
      'npu',
      'gpu',
      'cloud',
      'developer',
      'open source',
      'programming',
      'software',
      'medical device',
      'health tech',
      'biotech',
      'medtech',
      'life sciences',
      'health informatics',
      'clinical informatics',
      'biomedical',
      'pharmaceutical',
    ],
    noiseKeywords: ['entertainment', 'celebrity', 'gossip', 'football', 'basketball', 'lottery', 'travel', 'cooking'],
    commerceNoiseKeywords: [
      'flash sale',
      'coupon',
      'discount',
      'promo code',
      'deal of the day',
      'clearance',
      'buy now',
      'limited offer',
    ],
    tophubAllowKeywords: [
      'hacker news',
      'github',
      'product hunt',
      'science',
      'health',
      'medicine',
      'medical',
      'biology',
      'research',
      'technology',
      'artificial intelligence',
      'machine learning',
    ],
    tophubBlockKeywords: [
      'shopping',
      'ecommerce',
      'tiktok',
      'instagram',
      'snapchat',
      'pinterest',
    ],
    enSignalPattern:
      /(?<![a-z0-9])(ai|aigc|llm|gpt|openai|anthropic|deepseek|gemini|claude|robot|robotics|embodied|autonomous|machine learning|artificial intelligence|transformer|diffusion|agent|pathology|digital pathology|histopathology|medical imaging|healthcare|clinical|laboratory medicine|precision medicine|drug discovery|genomics|biomarker|radiology|telemedicine|whole slide imaging|computational pathology)(?![a-z0-9])/i,
  },
};
